services:
  db:
    image: mysql:8.0
    container_name: healthlog_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthlog_db
    ports:
      - "3307:3306"
    volumes:
      - healthlog_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  healthlog_data:
